name: Build wheels for Linux ARM

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels for Linux ARM
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Download MuPDF
        run: mkdir mupdf && wget -q 'https://mupdf.com/downloads/archive/mupdf-1.18.0-source.tar.gz' -O - | tar zx -C mupdf --strip-components=1

      - name: Update MuPDF Source
        run: cp fitz/_config.h mupdf/include/mupdf/fitz/config.h

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.0.0a2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT: "CFLAGS='-fPIC'"
          CIBW_ARCHS_LINUX: aarch64
          CIBW_SKIP: "pp* *i686"
          CIBW_BEFORE_ALL: "cd mupdf && make HAVE_X11=no HAVE_GLFW=no HAVE_GLUT=no prefix=/usr/local install && cd .."

      - uses: actions/upload-artifact@v2
        with:
          name: linux-arm-wheels
          path: ./wheelhouse/*.whl