name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Download MuPDF
        run: mkdir mupdf && wget -q 'https://mupdf.com/downloads/archive/mupdf-1.18.0-source.tar.gz' -O - | tar zx -C mupdf --strip-components=1
      - name: Build MuPDF
        run: export CFLAGS="-fPIC" && cd mupdf && make HAVE_X11=no HAVE_GLFW=no HAVE_GLUT=no prefix=/usr/local install && cd ..

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.0.0a2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT: "CFLAGS='-fPIC'"
          CIBW_SKIP: "pp* *i686"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl